import type { Project } from '../types/project';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    name: 'Pipeline de Analítica de Admisión y Triage en Urgencias',
    description: 'Ingesta continua de eventos HL7/FHIR y modelado predictivo de tiempo de espera y demanda de camas en Urgencias.',
    status: 'desarrollo',
    category: 'asistencial',
    area: 'Urgencias',
    tags: ['Big Data', 'Kafka', 'Spark Streaming', 'Predictive Analytics'],
    startDate: '2026-08-01',
    estimatedDeliveryDate: '2026-10-15',
    location: 'Cluster-Hadoop-02 / /apps/lakehouse/asistencial/urgencias',
    githubUrl: 'https://github.com/salud-data/urgencias-triage-streaming',
    assignee: 'Jerson Tapias',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-09-05T14:30:00Z'
  },
  {
    id: 'proj-002',
    name: 'Data Lakehouse de Facturación Electrónica y Glosas',
    description: 'Consolidación de cuentas médicas, auditoría automatizada y detección de patrones de glosas recurrentes.',
    status: 'pruebas',
    category: 'administrativo',
    area: 'Facturación & Cuentas Médicas',
    tags: ['ETL', 'Delta Lake', 'PySpark', 'Power BI'],
    startDate: '2026-07-15',
    estimatedDeliveryDate: '2026-09-25',
    location: 'Servidor BigData-01 / /opt/pipelines/billing-lake',
    githubUrl: 'https://github.com/salud-data/lakehouse-facturacion-glosas',
    assignee: 'Laura Gómez',
    createdAt: '2026-07-15T08:30:00Z',
    updatedAt: '2026-09-08T11:00:00Z'
  },
  {
    id: 'proj-003',
    name: 'Modelo de Pronóstico de Ocupación UCI y Desabastecimiento Farmacéutico',
    description: 'Redes neuronales y series temporales para optimizar compras y disponibilidad crítica de medicamentos.',
    status: 'pausado',
    category: 'asistencial',
    area: 'UCI & Farmacia Central',
    tags: ['Machine Learning', 'Python', 'TimeSeries', 'MLflow'],
    startDate: '2026-06-10',
    estimatedDeliveryDate: '2026-09-30',
    pauseReason: 'En espera de aprobación del comité de ética y habilitación de túnel seguro hacia el servidor central de farmacia.',
    location: 'Servidor ML-Inference-01 / /models/uci-pharma',
    githubUrl: 'https://github.com/salud-data/ml-uci-pharma-forecasting',
    assignee: 'Carlos Restrepo',
    createdAt: '2026-06-10T10:00:00Z',
    updatedAt: '2026-08-28T16:20:00Z'
  },
  {
    id: 'proj-004',
    name: 'Despliegue de Arquitectura de Telemetría Quirúrgica',
    description: 'Monitoreo en tiempo real de equipos biomédicos y tiempos de rotación de salas de cirugía.',
    status: 'despliegue',
    category: 'asistencial',
    area: 'Cirugía & Quirófanos',
    tags: ['IoT', 'Kafka', 'InfluxDB', 'Grafana'],
    startDate: '2026-07-01',
    estimatedDeliveryDate: '2026-09-18',
    location: 'Kubernetes Cluster Edge / namespace: edge-biomedical',
    githubUrl: 'https://github.com/salud-data/telemetria-quirofanos-edge',
    assignee: 'Santiago Vélez',
    createdAt: '2026-07-01T08:00:00Z',
    updatedAt: '2026-09-07T17:10:00Z'
  },
  {
    id: 'proj-005',
    name: 'Plataforma de Capacitación y Reportes de Gestión de Talento Humano',
    description: 'Módulos analíticos de rotación de personal, horas extras y ausentismo para líderes de área.',
    status: 'capacitacion',
    category: 'administrativo',
    area: 'Recursos Humanos & Nómina',
    tags: ['Dashboard', 'SQL', 'PostgreSQL', 'Metabase'],
    startDate: '2026-06-01',
    estimatedDeliveryDate: '2026-09-12',
    location: 'Servidor Analytics-Web / /var/www/talent-analytics',
    githubUrl: 'https://github.com/salud-data/talent-insights-dashboard',
    assignee: 'Marcela Ríos',
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-09-08T09:40:00Z'
  },
  {
    id: 'proj-006',
    name: 'Ingesta de Imágenes Diagnósticas DICOM y Metadatos Clínicos',
    description: 'Extracción de metadatos clínicos estructurados desde PACS para investigación oncológica.',
    status: 'analisis',
    category: 'asistencial',
    area: 'Radiología & Oncología',
    tags: ['Big Data', 'DICOM', 'Data Lake', 'Spark'],
    startDate: '2026-09-01',
    estimatedDeliveryDate: '2026-11-30',
    location: 'Data Lake S3 Compatible / bucket: pacs-oncology-lake',
    githubUrl: 'https://github.com/salud-data/pacs-dicom-metadata-extractor',
    assignee: 'Jerson Tapias',
    createdAt: '2026-09-01T11:00:00Z',
    updatedAt: '2026-09-06T15:10:00Z'
  },
  {
    id: 'proj-007',
    name: 'Motor de Conciliación Bancaria y Pagos de EPS',
    description: 'Procesamiento automatizado de extractos bancarios masivos y cruce con pagos de aseguradoras.',
    status: 'retrasado',
    category: 'administrativo',
    area: 'Tesorería & Contabilidad',
    tags: ['ETL', 'Python', 'Airflow', 'SQL Server'],
    startDate: '2026-05-20',
    estimatedDeliveryDate: '2026-08-30',
    location: 'Servidor Airflow-Worker-03 / /dags/treasury/eps-recon',
    githubUrl: 'https://github.com/salud-data/conciliacion-eps-airflow',
    assignee: 'Andrés Morales',
    createdAt: '2026-05-20T08:30:00Z',
    updatedAt: '2026-09-04T12:00:00Z'
  },
  {
    id: 'proj-008',
    name: 'Auditoría de Acceso a Historias Clínicas y Cumplimiento Normativo',
    description: 'Sistema de trazabilidad de accesos y logs de seguridad para auditorías de privacidad de datos.',
    status: 'entregado',
    category: 'administrativo',
    area: 'Tecnología & Seguridad',
    tags: ['Big Data', 'Elasticsearch', 'Logstash', 'Kibana'],
    startDate: '2026-03-01',
    estimatedDeliveryDate: '2026-06-30',
    actualDeliveryDate: '2026-06-28',
    location: 'Servidor SIEM-Elastic-Cluster / index: audit-ehr-*',
    githubUrl: 'https://github.com/salud-data/audit-ehr-compliance',
    assignee: 'Felipe Vargas',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-06-28T18:00:00Z'
  },
  {
    id: 'proj-009',
    name: 'Dashboard Ejecutivo de Indicadores de Calidad Asistencial (Resolución 256)',
    description: 'Centralización de indicadores obligatorios de calidad, eventos adversos y tiempos de atención.',
    status: 'entregado',
    category: 'asistencial',
    area: 'Calidad & Dirección Médica',
    tags: ['Power BI', 'Data Warehouse', 'SSAS', 'Healthcare KPI'],
    startDate: '2026-02-15',
    estimatedDeliveryDate: '2026-05-15',
    actualDeliveryDate: '2026-05-14',
    location: 'Power BI Service / Workspace: Calidad Asistencial Corporativa',
    githubUrl: 'https://github.com/salud-data/indicadores-calidad-256',
    assignee: 'Laura Gómez',
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-05-14T17:30:00Z'
  },
  {
    id: 'proj-010',
    name: 'Pipeline de Facturación Electrónica DIAN 2.1 Masiva',
    description: 'Generación y envío XML firmado para facturas de servicios ambulatorios y hospitalarios.',
    status: 'terminado',
    category: 'administrativo',
    area: 'Facturación & Cuentas Médicas',
    tags: ['API REST', 'Java', 'Spring Boot', 'ActiveMQ'],
    startDate: '2026-04-01',
    estimatedDeliveryDate: '2026-07-20',
    actualDeliveryDate: '2026-07-19',
    location: 'Servidor App-Backend-04 / /opt/dian-invoicing-service',
    githubUrl: 'https://github.com/salud-data/facturacion-dian-service',
    assignee: 'Carlos Restrepo',
    createdAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-07-19T16:00:00Z'
  }
];
